---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hunter14/public_html
    - /bin/cp -R index.html $DEPLOYPATH/
    - /bin/cp -R methodology.html $DEPLOYPATH/
    - /bin/cp -R projects.html $DEPLOYPATH/
    - /bin/cp -R css $DEPLOYPATH/
    - /bin/cp -R js $DEPLOYPATH/
    - /bin/cp -R photos $DEPLOYPATH/
